# Generated by Django 2.2 on 2020-03-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20200323_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='like',
            field=models.ManyToManyField(related_name='likes', to='quotes.User'),
        ),
    ]
